INSERT INTO lines (line_number, name, direction) VALUES
('1', 'Bunje - Poljička - HNK - Dom Rata', 'Loop'),
('2', 'Split - Zračna luka (Kaštela)', 'Both'),
('2A', 'Kaštel Sućurac (Strinje) - Trajektna luka', 'Loop'),
('3', 'Brnik - Brda', 'Loop'),
('3A', 'Brnik - Poljička', 'Loop'),
('5', 'Dračevac - HNK', 'Loop'),
('5A', 'Dračevac - Solin - HNK', 'Loop'),
('6', 'Kila - HNK', 'Loop'),
('7', 'Žnjan - Zapadna obala', 'Both'),
('8', 'Žnjan - Zvončac', 'Both'),
('9', 'Ravne Njive - Trajektna luka', 'Loop'),
('10', 'Japirko - Trajektna luka', 'Loop'),
('11', 'Spinut - Kampus - Pujanke - Ravne Njive', 'Both'),
('12', 'Sv. Frane - Bene', 'Both'),
('13', 'Spinut - Žnjan - Duilovo', 'Both'),
('14', 'Brda - Kopilica - Bolnice - Duilovo - Žnjan', 'Both'),
('15', 'Duilovo - Trajektna luka', 'Loop'),
('16', 'Ninčevići - Dom Rata - HNK - Poljička', 'Loop'),
('17', 'Spinut - Lora - Kampus - Trstenik', 'Both'),
('18', 'Sirobuja - HNK', 'Loop'),
('21', 'Sv. Frane - Zenta', 'Loop'),
('22', 'Split - Klis', 'Both'),
('24', 'Split - TTTS', 'Both'),
('25', 'Split - Stobreč', 'Both'),
('26', 'Split - Kamen', 'Both'),
('27', 'Split - Korešnica - Žrnovnica', 'Both'),
('31', 'Split - Vranjic', 'Both'),
('32', 'Split - Kučine', 'Both'),
('33', 'Split - Klis Kosa', 'Both'),
('37', 'Split - Airport - Trogir', 'Both'),
('38', 'Split - Kaštel Stari - Zračna luka', 'Both');
